const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), date=v=>new Date(v+'T12:00:00').toLocaleDateString('pt-BR');
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const today=new Date().toISOString().slice(0,10);
const seed={
 sales:[],
 expenses:[],
 campaigns:[{id:'c1',platform:'Meta Ads',name:'Remarketing Agosto',start:today,end:today,value:540,notes:'Conversões WhatsApp'}],
 partners:[{id:'p1',name:'Canal Rbx News',contact:'@rbxnews',type:'Divulgação',value:300,frequency:'Mensal',due:today,status:'Pendente',paid:900}],
 commissions:[{id:'m1',name:'João',sale:'s1',value:20,date:today,status:'Pago',notes:''},{id:'m2',name:'Marina',sale:'s3',value:15,date:today,status:'Pendente',notes:''}],
 categories:[{id:'cat1',name:'Blox Fruits',icon:'⚔',fields:['Level','Frutas ingeridas','Frutas no inventário','Espadas','Guns','Fighting Styles','Acessórios','Raça','V4','Fragmentos','Beli','Gamepasses','Títulos','Sea liberado']},{id:'cat2',name:'Grow a Garden',icon:'🌱',fields:['Pets','Sementes','Dinheiro','Eventos','Itens raros','Gamepasses']},{id:'cat3',name:'Grow a Garden 2',icon:'🌿',fields:['Pets','Sementes','Dinheiro','Eventos','Itens raros','Gamepasses']},{id:'cat4',name:'Plants Vs Brainrots',icon:'🌻',fields:['Personagens','Itens','Gamepasses']},{id:'cat5',name:'Steal a Brainrots',icon:'🧠',fields:['Brainrots','Dinheiro','Itens raros']},{id:'cat6',name:'99 Noites na Floresta',icon:'🌲',fields:['Itens','Recursos','Nível','Equipamentos','Gamepasses']}],
 accounts:[{id:'a1',name:'Dragon V4 Full',login:'player_x',password:'••••••••',email:'conta@email.com',emailPassword:'••••••••',category:'Blox Fruits',buy:120,sell:349.9,status:'Disponível',attrs:{Level:'2550',Raça:'Ghoul',V4:'Sim'}},{id:'a2',name:'Garden Pets Pack',login:'garden_44',password:'••••••••',email:'garden@email.com',emailPassword:'••••••••',category:'Grow a Garden',buy:70,sell:189.9,status:'Reservada',attrs:{Pets:'Dragonfly, Raccoon'}},{id:'a3',name:'Brainrot Rare',login:'rare_br',password:'••••••••',email:'rare@email.com',emailPassword:'••••••••',category:'Steal a Brainrots',buy:95,sell:279.9,status:'Vendida',attrs:{Brainrots:'Tralalero, Bombardiro'}}],
 users:[{id:'u1',name:'Administrador',email:'admin@pixelsale.com',role:'Administrador',status:'Ativo'}]
};
let db=JSON.parse(localStorage.getItem('pixelsale-db')||'null')||seed;
const dataResetVersion='2026-08-02-sales-expenses';
if(localStorage.getItem('pixelsale-data-reset')!==dataResetVersion){
  db.sales=[];
  db.expenses=[];
  localStorage.setItem('pixelsale-db',JSON.stringify(db));
  localStorage.setItem('pixelsale-data-reset',dataResetVersion);
}
let page='dashboard';
const save=()=>localStorage.setItem('pixelsale-db',JSON.stringify(db));
const nav=[['Visão geral','dashboard','▦','Dashboard'],['Operação','sales','↗','Vendas'],['Operação','inventory','◇','Contas Roblox'],['Financeiro','finance','◉','Financeiro'],['Financeiro','traffic','⌁','Tráfego pago'],['Relacionamentos','partners','♧','Parcerias'],['Relacionamentos','commissions','♙','Comissões'],['Gestão','reports','▥','Relatórios'],['Gestão','admin','⚙','Administração']];
function renderNav(){let last='';$('#nav').innerHTML=nav.map(n=>{let s=n[0]!==last?`<div class="nav-section">${last=n[0]}</div>`:'';return s+`<button class="nav-btn ${page===n[1]?'active':''}" data-page="${n[1]}"><span class="nav-icon">${n[2]}</span>${n[3]}</button>`}).join('');$$('.nav-btn').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();$('#sidebar').classList.remove('open')})}
const head=(t,s,actions='')=>`<div class="page-head"><div><h1>${t}</h1><p>${s}</p></div><div class="head-actions">${actions}</div></div>`;
const kpi=(label,value,icon='↗',color='var(--purple)',trend='Atualizado agora')=>`<div class="kpi" style="--accent:${color}"><div class="kpi-top"><span>${label}</span><span class="kpi-icon">${icon}</span></div><strong>${value}</strong><span class="trend">${trend}</span></div>`;
const profit=s=>+s.value-+s.cost-+(s.commission||0)-+(s.partnership||0);
function dashboard(){let revenue=db.sales.filter(s=>s.status==='Concluída').reduce((a,s)=>a + +s.value,0),costs=db.sales.reduce((a,s)=>a + +s.cost,0),ads=db.campaigns.reduce((a,s)=>a + +s.value,0),exp=db.expenses.reduce((a,s)=>a + +s.value,0),paid=db.commissions.filter(c=>c.status==='Pago').reduce((a,c)=>a + +c.value,0),pending=db.commissions.filter(c=>c.status==='Pendente').reduce((a,c)=>a + +c.value,0),net=revenue-costs-ads-exp-paid,bars=[34,54,42,68,59,85,74,96,66,81,92,88];return head('Dashboard','Visão geral do desempenho da PixelSale',`<button class="secondary" onclick="exportCSV('sales')">⇩ Exportar</button><button class="primary" onclick="openForm('sale')">＋ Nova venda</button>`)+`<div class="kpi-grid">${kpi('Faturamento bruto',money(revenue),'↗','var(--purple)','↑ 12,5% vs. mês anterior')}${kpi('Lucro líquido',money(net),'◇','var(--green)','↑ 8,2% vs. mês anterior')}${kpi('Despesas totais',money(exp+ads+costs),'▤','var(--red)','Custos operacionais')}${kpi('Lucro mensal',money(net),'◉','var(--blue)','Resultado do mês atual')}${kpi('Total de vendas',db.sales.length,'▣','var(--blue)','Pedidos registrados')}${kpi('Ticket médio',money(revenue/(db.sales.length||1)),'◉','var(--yellow)','Média por venda')}${kpi('Comissões pagas',money(paid),'✓','var(--green)','Valores liquidados')}${kpi('Comissões pendentes',money(pending),'!','var(--yellow)','Aguardando pagamento')}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h3>Evolução financeira</h3><span class="muted">Receita × despesas · 12 meses</span></div><div class="chart">${bars.map((b,i)=>`<div class="bar-group"><i class="bar" style="height:${b}%"></i><i class="bar alt" style="height:${Math.max(12,b-28)}%"></i><label>${['Set','Out','Nov','Dez','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago'][i]}</label></div>`).join('')}</div></div><div class="panel"><div class="panel-head"><h3>Distribuição de gastos</h3><span class="muted">Mês atual</span></div><div class="donut-wrap"><div class="donut"></div><div class="legend"><div style="--c:var(--purple)">Produtos · 45%</div><div style="--c:var(--blue)">Tráfego · 25%</div><div style="--c:var(--yellow)">Parcerias · 17%</div><div style="--c:var(--red)">Outros · 13%</div></div></div></div></div>${salesTable(db.sales.slice(0,5),'Vendas recentes')}`}
const statusClass=s=>/Concluída|Disponível|Pago|Ativo/.test(s)?'green':/Pendente|Reservada/.test(s)?'yellow':'red';
function salesTable(rows,title='Todas as vendas'){return `<div class="panel table-panel"><div class="panel-head"><h3>${title}</h3><span class="muted">${rows.length} registros</span></div><table><thead><tr><th>Cliente / Produto</th><th>Categoria</th><th>Valor</th><th>Lucro</th><th>Pagamento</th><th>Data</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td><b>${s.client}</b><br><span class="muted">${s.product}</span></td><td>${s.category}</td><td>${money(s.value)}</td><td style="color:var(--green)">${money(profit(s))}</td><td>${s.payment}</td><td>${date(s.date)}</td><td><span class="badge ${statusClass(s.status)}">${s.status}</span></td><td><button class="action" onclick="removeItem('sales','${s.id}')">×</button></td></tr>`).join('')||`<tr><td colspan="8" class="empty"><b>Nenhuma venda encontrada</b>Cadastre sua primeira venda.</td></tr>`}</tbody></table></div>`}
function sales(){return head('Gestão de vendas','Cadastre, acompanhe e filtre todas as vendas',`<button class="primary" onclick="openForm('sale')">＋ Cadastrar venda</button>`)+`<div class="filters"><input class="input" id="saleSearch" placeholder="Buscar cliente ou produto"><select id="saleStatus"><option value="">Todos os status</option><option>Concluída</option><option>Pendente</option><option>Cancelada</option></select><select id="saleCategory"><option value="">Todas as categorias</option>${db.categories.map(c=>`<option>${c.name}</option>`).join('')}</select></div><div id="salesResult">${salesTable(db.sales)}</div>`}
function inventory(){let available=db.accounts.filter(a=>a.status==='Disponível'), invested=db.accounts.reduce((x,a)=>x + +a.buy,0), potential=db.accounts.filter(a=>a.status!=='Vendida').reduce((x,a)=>x + +a.sell,0);return head('Contas Roblox','Estoque inteligente com atributos personalizados',`<button class="secondary" onclick="openForm('category')">＋ Categoria</button><button class="primary" onclick="openForm('account')">＋ Nova conta</button>`)+`<div class="kpi-grid">${kpi('Disponíveis',available.length,'◇','var(--green)')}${kpi('Vendidas',db.accounts.filter(a=>a.status==='Vendida').length,'✓','var(--blue)')}${kpi('Valor investido',money(invested),'▤','var(--yellow)')}${kpi('Venda potencial',money(potential),'↗','var(--purple)')}</div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Estoque por categoria</h3><span class="muted">Categorias editáveis</span></div><div class="stock-grid">${db.categories.map(c=>{let arr=db.accounts.filter(a=>a.category===c.name),av=arr.filter(a=>a.status==='Disponível').length;return `<div class="stock-card"><div class="game"><div class="game-icon">${c.icon}</div><div><h3>${c.name}</h3><p>${c.fields.length} atributos personalizados</p></div></div><div class="stock-stats"><span>DISPONÍVEL<b>${av}</b></span><span>TOTAL<b>${arr.length}</b></span><span>POTENCIAL<b>${money(arr.reduce((x,a)=>x + +a.sell,0))}</b></span></div><div class="progress"><i style="width:${arr.length?av/arr.length*100:0}%"></i></div></div>`}).join('')}</div></div><div class="panel table-panel"><div class="panel-head"><h3>Contas cadastradas</h3><span class="muted">${db.accounts.length} contas</span></div><table><thead><tr><th>Conta</th><th>Categoria</th><th>Compra</th><th>Venda</th><th>Margem</th><th>Status</th><th></th></tr></thead><tbody>${db.accounts.map(a=>`<tr><td><b>${a.name}</b><br><span class="muted">${a.login}</span></td><td>${a.category}</td><td>${money(a.buy)}</td><td>${money(a.sell)}</td><td style="color:var(--green)">${money(a.sell-a.buy)}</td><td><span class="badge ${statusClass(a.status)}">${a.status}</span></td><td><button class="action" onclick="removeItem('accounts','${a.id}')">×</button></td></tr>`).join('')}</tbody></table></div>`}
function genericPage(type,title,sub,columns,formType){let rows=db[type];return head(title,sub,`<button class="primary" onclick="openForm('${formType}')">＋ Novo registro</button>`)+`<div class="kpi-grid">${kpi('Total registrado',rows.length,'▦','var(--blue)')}${kpi('Volume financeiro',money(rows.reduce((a,x)=>a+ +(x.value||0),0)),'↗','var(--green)')}${kpi('Pendentes',rows.filter(x=>x.status==='Pendente').length,'!','var(--yellow)')}${kpi('Atualizados hoje',rows.filter(x=>(x.date||x.start||x.due)===today).length,'✓','var(--purple)')}</div><div class="panel table-panel"><div class="panel-head"><h3>${title}</h3><span class="muted">${rows.length} registros</span></div><table><thead><tr>${columns.map(c=>`<th>${c[0]}</th>`).join('')}<th></th></tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td>${c[2]==='money'?money(r[c[1]]):c[2]==='date'?date(r[c[1]]):c[1]==='status'?`<span class="badge ${statusClass(r[c[1]])}">${r[c[1]]}</span>`:(r[c[1]]||'—')}</td>`).join('')}<td><button class="action" onclick="removeItem('${type}','${r.id}')">×</button></td></tr>`).join('')||`<tr><td colspan="${columns.length+1}" class="empty"><b>Nenhum registro</b>Use o botão acima para começar.</td></tr>`}</tbody></table></div>`}
function finance(){return genericPage('expenses','Controle financeiro','Receitas e despesas em um só lugar',[['Descrição','description'],['Categoria','category'],['Valor','value','money'],['Pagamento','payment'],['Data','date','date']],'expense')}
function traffic(){return genericPage('campaigns','Tráfego pago','Controle de campanhas e investimento em mídia',[['Campanha','name'],['Plataforma','platform'],['Investimento','value','money'],['Início','start','date'],['Fim','end','date']],'campaign')}
function partners(){return genericPage('partners','Gestão de parcerias','Acordos, vencimentos e histórico de pagamentos',[['Parceiro','name'],['Tipo','type'],['Valor acordado','value','money'],['Frequência','frequency'],['Vencimento','due','date'],['Status','status']],'partner')}
function commissionTable(rows,title,dateLabel){return `<div class="panel table-panel"><div class="panel-head"><h3>${title}</h3><span class="muted">${rows.length} registros</span></div><table><thead><tr><th>Nome</th><th>Valor</th><th>${dateLabel}</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><b>${c.name}</b></td><td>${money(c.value)}</td><td>${date(c.date)}</td><td><span class="badge ${statusClass(c.status)}">${c.status}</span></td><td><button class="action" onclick="removeItem('commissions','${c.id}')">×</button></td></tr>`).join('')||`<tr><td colspan="5" class="empty"><b>Nenhuma comissão</b>Não há valores nesta situação.</td></tr>`}</tbody></table></div>`}
function commissions(){let paid=db.commissions.filter(c=>c.status==='Pago'),pending=db.commissions.filter(c=>c.status==='Pendente'),paidTotal=paid.reduce((a,c)=>a + +c.value,0),pendingTotal=pending.reduce((a,c)=>a + +c.value,0);return head('Gestão de comissões','Pagamentos organizados por situação',`<button class="primary" onclick="openForm('commission')">＋ Nova comissão</button>`)+`<div class="commission-summary"><div class="commission-box paid"><span>TOTAL PAGO</span><strong>${money(paidTotal)}</strong></div><div class="commission-box pending"><span>TOTAL PENDENTE</span><strong>${money(pendingTotal)}</strong></div></div>${commissionTable(pending,'Comissões pendentes','Data prevista')}${commissionTable(paid,'Comissões pagas','Data do pagamento')}`}
function reports(){return head('Relatórios','Analise e exporte os resultados da operação',`<button class="secondary" onclick="window.print()">▣ Salvar PDF</button><button class="primary" onclick="exportCSV('sales')">⇩ Exportar Excel</button>`)+`<div class="filters"><input type="date" class="input" value="${today}"><select><option>Todas as categorias</option>${db.categories.map(c=>`<option>${c.name}</option>`)}</select><button class="secondary">Aplicar filtros</button></div>${dashboard().split('<div class="grid-2">')[1]}`}
function admin(){return head('Administração','Usuários, acessos e configuração do sistema',`<button class="primary" onclick="openForm('user')">＋ Novo usuário</button>`)+`<div class="grid-2"><div class="panel table-panel" style="margin-top:0"><div class="panel-head"><h3>Usuários e permissões</h3></div><table><thead><tr><th>Usuário</th><th>Email</th><th>Perfil</th><th>Status</th></tr></thead><tbody>${db.users.map(u=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.role}</td><td><span class="badge green">${u.status}</span></td></tr>`).join('')}</tbody></table></div><div class="panel"><div class="panel-head"><h3>Perfis de acesso</h3></div><div class="notice-list"><div class="notice"><span class="notice-icon">♛</span><div><b>Administrador</b><p>Acesso completo a todos os módulos.</p></div></div><div class="notice"><span class="notice-icon">▤</span><div><b>Financeiro</b><p>Vendas, despesas e relatórios financeiros.</p></div></div><div class="notice"><span class="notice-icon">♙</span><div><b>Funcionário</b><p>Operação de vendas e estoque.</p></div></div></div></div></div><div class="panel" style="margin-top:14px"><div class="panel-head"><h3>Categorias e atributos dinâmicos</h3><button class="secondary" onclick="openForm('category')">＋ Adicionar</button></div>${db.categories.map(c=>`<div class="notice"><span class="notice-icon">${c.icon}</span><div><b>${c.name}</b><p>${c.fields.join(' · ')}</p></div></div>`).join('')}</div>`}
const renderers={dashboard,sales,inventory,finance,traffic,partners,commissions,reports,admin};
function render(){renderNav();$('#content').innerHTML=renderers[page]();if(page==='sales'){const filter=()=>{let q=$('#saleSearch').value.toLowerCase(),st=$('#saleStatus').value,cat=$('#saleCategory').value;$('#salesResult').innerHTML=salesTable(db.sales.filter(s=>(s.client+s.product).toLowerCase().includes(q)&&(!st||s.status===st)&&(!cat||s.category===cat)))};['saleSearch','saleStatus','saleCategory'].forEach(id=>$('#'+id).oninput=filter)}updateNotifications()}
const forms={
 sale:['Nova venda','Registre a venda e calcule o lucro automaticamente',[['client','Cliente','text'],['product','Produto','text'],['category','Categoria','category'],['value','Valor da venda','number'],['cost','Custo do produto','number'],['commission','Comissão','number'],['partnership','Parceria','number'],['payment','Forma de pagamento','select:PIX,Cartão,Boleto,Dinheiro'],['platform','Plataforma','text'],['date','Data','date'],['status','Status','select:Concluída,Pendente,Cancelada']],'sales'],
 account:['Nova conta Roblox','Credenciais e dados do estoque',[['name','Nome da conta','text'],['login','Login','text'],['password','Senha','text'],['email','Email','email'],['emailPassword','Senha do email','text'],['category','Categoria','category'],['buy','Valor de compra','number'],['sell','Valor de venda','number'],['status','Status','select:Disponível,Reservada,Vendida']],'accounts'],
 expense:['Nova despesa','Registre uma saída financeira',[['description','Descrição','text'],['category','Categoria','select:Compra de contas,Compra de itens,Produtos,Serviços,Hospedagem,Domínio,Ferramentas,Outros'],['value','Valor','number'],['date','Data','date'],['payment','Forma de pagamento','select:PIX,Cartão,Boleto,Dinheiro'],['notes','Observação','textarea']],'expenses'],
 campaign:['Nova campanha','Acompanhe o investimento em anúncios',[['platform','Plataforma','select:Google Ads,Meta Ads,TikTok Ads'],['name','Nome da campanha','text'],['start','Data inicial','date'],['end','Data final','date'],['value','Valor investido','number'],['notes','Observações','textarea']],'campaigns'],
 partner:['Novo parceiro','Cadastre acordos e vencimentos',[['name','Nome','text'],['contact','Contato','text'],['type','Tipo da parceria','text'],['value','Valor acordado','number'],['frequency','Frequência','select:Semanal,Quinzenal,Mensal,Personalizada'],['due','Próximo vencimento','date'],['status','Status','select:Ativo,Pendente,Inativo']],'partners'],
 commission:['Nova comissão','Relacione o pagamento ao colaborador',[['name','Colaborador / Afiliado','text'],['sale','Venda relacionada','sale'],['value','Valor','number'],['date','Data','date'],['status','Status','select:Pago,Pendente'],['notes','Observação','textarea']],'commissions'],
 category:['Nova categoria','Defina atributos sem alterar o sistema',[['name','Nome da categoria','text'],['icon','Ícone (emoji)','text'],['fields','Atributos (separados por vírgula)','textarea']],'categories'],
 user:['Novo usuário','Configure o acesso ao sistema',[['name','Nome','text'],['email','Email','email'],['role','Perfil','select:Administrador,Funcionário,Financeiro'],['status','Status','select:Ativo,Inativo']],'users']
};
function inputField(f){let [name,label,type]=f,val=(type==='date'?today:'');if(type==='category')return `<div class="field"><label>${label}</label><select name="${name}" required>${db.categories.map(c=>`<option>${c.name}</option>`).join('')}</select></div>`;if(type==='sale')return `<div class="field"><label>${label}</label><select name="${name}" required>${db.sales.map(s=>`<option value="${s.id}">${s.client} — ${s.product}</option>`).join('')}</select></div>`;if(type.startsWith('select:'))return `<div class="field"><label>${label}</label><select name="${name}">${type.slice(7).split(',').map(x=>`<option>${x}</option>`).join('')}</select></div>`;if(type==='textarea')return `<div class="field full"><label>${label}</label><textarea name="${name}" rows="3"></textarea></div>`;return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" value="${val}" ${type!=='number'?'required':''}></div>`}
function openForm(type){let f=forms[type];$('#modalBody').innerHTML=`<h2>${f[0]}</h2><div class="modal-sub">${f[1]}</div><form id="dataForm"><div class="form-grid">${f[2].map(inputField).join('')}<div id="dynamicFields" class="field full"></div></div><div class="form-actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Salvar registro</button></div></form>`;$('#modal').classList.add('open');if(type==='account'){let sel=$('[name=category]');const dynamic=()=>{let c=db.categories.find(x=>x.name===sel.value);$('#dynamicFields').innerHTML=`<label>Atributos de ${c.name}</label><div class="form-grid">${c.fields.map(x=>`<div class="field"><input data-attr="${x}" placeholder="${x}"></div>`).join('')}</div>`};sel.onchange=dynamic;dynamic()}$('#dataForm').onsubmit=e=>{e.preventDefault();let obj=Object.fromEntries(new FormData(e.target));f[2].filter(x=>x[2]==='number').forEach(x=>obj[x[0]]=+(obj[x[0]]||0));obj.id=uid();if(type==='category')obj.fields=obj.fields.split(',').map(x=>x.trim()).filter(Boolean);if(type==='account')obj.attrs=Object.fromEntries($$('[data-attr]').map(x=>[x.dataset.attr,x.value]).filter(x=>x[1]));if(type==='partner')obj.paid=0;db[f[3]].unshift(obj);save();closeModal();showToast('Registro salvo com sucesso');render()}}
function closeModal(){$('#modal').classList.remove('open')}
function removeItem(type,id){if(confirm('Deseja remover este registro?')){db[type]=db[type].filter(x=>x.id!==id);save();render();showToast('Registro removido')}}
function showToast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}
function updateNotifications(){let n=db.partners.filter(p=>p.status==='Pendente').length+db.commissions.filter(c=>c.status==='Pendente').length;$('#notifyCount').textContent=n;$('#notifyCount').style.display=n?'block':'none'}
function exportCSV(type){let rows=db[type];if(!rows.length)return;let keys=[...new Set(rows.flatMap(Object.keys))].filter(k=>k!=='attrs'),csv=[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pixelsale-${type}.csv`;a.click();URL.revokeObjectURL(a.href)}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target===$('#modal'))closeModal()};$('#quickAdd').onclick=()=>openForm('sale');$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#notifyBtn').onclick=()=>{let pending=[...db.partners.filter(p=>p.status==='Pendente').map(p=>`Parceiro: ${p.name}`),...db.commissions.filter(c=>c.status==='Pendente').map(c=>`Comissão: ${c.name}`)];$('#modalBody').innerHTML=`<h2>Central de notificações</h2><div class="modal-sub">Pendências que precisam de atenção</div><div class="notice-list">${pending.map(x=>`<div class="notice"><span class="notice-icon">!</span><div><b>${x}</b><p>Pagamento pendente ou próximo do vencimento.</p></div></div>`).join('')||'<div class="empty">Tudo em dia por aqui.</div>'}</div>`;$('#modal').classList.add('open')};$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){page='sales';render();$('#saleSearch').value=e.target.value;$('#saleSearch').dispatchEvent(new Event('input'))}};

const auth={key:'pixelsale-session',isActive(){return sessionStorage.getItem(this.key)==='active'||localStorage.getItem(this.key)==='active'},login(remember){(remember?localStorage:sessionStorage).setItem(this.key,'active')},logout(){localStorage.removeItem(this.key);sessionStorage.removeItem(this.key)}};
function showApp(){ $('#loginScreen').classList.add('is-hidden');$('#appShell').classList.remove('is-locked');render() }
function showLogin(){ $('#loginScreen').classList.remove('is-hidden');$('#appShell').classList.add('is-locked') }
$('#loginForm').onsubmit=e=>{e.preventDefault();let data=Object.fromEntries(new FormData(e.target));if(data.email.toLowerCase()==='admin@pixelsale.com'&&data.password==='47g?U&hs%1L1'){auth.login(Boolean(data.remember));$('#loginError').classList.remove('show');showApp()}else{$('#loginError').classList.add('show')}};
$('#togglePassword').onclick=()=>{let input=$('#loginForm [name=password]');input.type=input.type==='password'?'text':'password'};
$('#forgotPassword').onclick=()=>showToast('Contate o administrador para redefinir sua senha.');
$('#logoutBtn').onclick=()=>{auth.logout();showLogin()};
if(auth.isActive())showApp();else showLogin();
